# UCX Browser - Chromium source code archive
# Built by KGECMD (Kayan Erkama)
# Project: UCX (Universally Created Xternal Privacy Project)
# NOTE: Substitutions beginning with underscore are provided by utils
[chromium]
url = https://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/%(_revision)s/chromium_linux.zip
output_path = ./
download_filename = chromium-%(_chromium_version)s.tar.xz
strip_leading_dirs = chromium-%(_chromium_version)s
